  &&lbl_CONSTBYTE,
  &&lbl_CONSTSHORT,
  &&lbl_SWITCH,
  &&lbl_BRANCH,
  &&lbl_BRANCHIF,
  &&lbl_BRANCHIFNOT,
  &&lbl_POPBRANCHIFNOT,
  &&lbl_BRANCHIFNEQTAG,
  &&lbl_BRANCHIFEQ,
  &&lbl_BRANCHIFNEQ,
  &&lbl_BRANCHIFLT,
  &&lbl_BRANCHIFGT,
  &&lbl_BRANCHIFLE,
  &&lbl_BRANCHIFGE,
  &&lbl_BRANCHINTERVAL,
  &&lbl_C_CALL1,
  &&lbl_C_CALL2,
  &&lbl_C_CALL3,
  &&lbl_C_CALL4,
  &&lbl_C_CALL5,
  &&lbl_C_CALLN,
  &&lbl_MAKEBLOCK,
  &&lbl_MAKEBLOCK1,
  &&lbl_MAKEBLOCK2,
  &&lbl_MAKEBLOCK3,
  &&lbl_MAKEBLOCK4,
  &&lbl_TAGOF,
  &&lbl_ACCESS,
  &&lbl_ACC0,
  &&lbl_ACC1,
  &&lbl_ACC2,
  &&lbl_ACC3,
  &&lbl_ACC4,
  &&lbl_ACC5,
  &&lbl_ACC6,
  &&lbl_ACC7,
  &&lbl_PUSHACC,
  &&lbl_PUSHACC0,
  &&lbl_PUSHACC1,
  &&lbl_PUSHACC2,
  &&lbl_PUSHACC3,
  &&lbl_PUSHACC4,
  &&lbl_PUSHACC5,
  &&lbl_PUSHACC6,
  &&lbl_PUSHACC7,
  &&lbl_ENVACC,
  &&lbl_ENV1,
  &&lbl_ENV2,
  &&lbl_ENV3,
  &&lbl_ENV4,
  &&lbl_ENV5,
  &&lbl_ENV6,
  &&lbl_ENV7,
  &&lbl_PUSHENVACC,
  &&lbl_PUSHENV1,
  &&lbl_PUSHENV2,
  &&lbl_PUSHENV3,
  &&lbl_PUSHENV4,
  &&lbl_PUSHENV5,
  &&lbl_PUSHENV6,
  &&lbl_PUSHENV7,
  &&lbl_PUSH_ENV1_APPLY1,
  &&lbl_PUSH_ENV1_APPLY2,
  &&lbl_PUSH_ENV1_APPLY3,
  &&lbl_PUSH_ENV1_APPLY4,
  &&lbl_PUSH_ENV1_APPTERM1,
  &&lbl_PUSH_ENV1_APPTERM2,
  &&lbl_PUSH_ENV1_APPTERM3,
  &&lbl_PUSH_ENV1_APPTERM4,
  &&lbl_PUSHATOM,
  &&lbl_ATOM,
  &&lbl_PUSHATOM0,
  &&lbl_ATOM0,
  &&lbl_ATOM1,
  &&lbl_ATOM2,
  &&lbl_ATOM3,
  &&lbl_ATOM4,
  &&lbl_ATOM5,
  &&lbl_ATOM6,
  &&lbl_ATOM7,
  &&lbl_ATOM8,
  &&lbl_ATOM9,
  &&lbl_CONSTINT,
  &&lbl_PUSHCONSTINT,
  &&lbl_CONST0,
  &&lbl_CONST1,
  &&lbl_CONST2,
  &&lbl_CONST3,
  &&lbl_PUSHCONST0,
  &&lbl_PUSHCONST1,
  &&lbl_PUSHCONST2,
  &&lbl_PUSHCONST3,
  &&lbl_GETFIELD,
  &&lbl_GETFIELD0,
  &&lbl_GETFIELD1,
  &&lbl_GETFIELD2,
  &&lbl_GETFIELD3,
  &&lbl_GETFIELD0_0,
  &&lbl_GETFIELD0_1,
  &&lbl_GETFIELD1_0,
  &&lbl_GETFIELD1_1,
  &&lbl_SETFIELD,
  &&lbl_SETFIELD0,
  &&lbl_SETFIELD1,
  &&lbl_SETFIELD2,
  &&lbl_SETFIELD3,
  &&lbl_GETGLOBAL,
  &&lbl_PUSH_GETGLOBAL,
  &&lbl_PUSH_GETGLOBAL_APPLY1,
  &&lbl_PUSH_GETGLOBAL_APPLY2,
  &&lbl_PUSH_GETGLOBAL_APPLY3,
  &&lbl_PUSH_GETGLOBAL_APPLY4,
  &&lbl_PUSH_GETGLOBAL_APPTERM1,
  &&lbl_PUSH_GETGLOBAL_APPTERM2,
  &&lbl_PUSH_GETGLOBAL_APPTERM3,
  &&lbl_PUSH_GETGLOBAL_APPTERM4,
  &&lbl_SETGLOBAL,
  &&lbl_PUSH_RETADDR,
  &&lbl_APPLY,
  &&lbl_APPLY1,
  &&lbl_APPLY2,
  &&lbl_APPLY3,
  &&lbl_APPLY4,
  &&lbl_APPTERM,
  &&lbl_APPTERM1,
  &&lbl_APPTERM2,
  &&lbl_APPTERM3,
  &&lbl_APPTERM4,
  &&lbl_RESTART,
  &&lbl_GRAB,
  &&lbl_RETURN1,
  &&lbl_RETURN2,
  &&lbl_RETURN,
  &&lbl_CLOSURE,
  &&lbl_CLOSREC,
  &&lbl_DUMMY,
  &&lbl_UPDATE,
  &&lbl_PUSHTRAP,
  &&lbl_RAISE,
  &&lbl_POPTRAP,
  &&lbl_SWAP,
  &&lbl_PUSH,
  &&lbl_POP,
  &&lbl_ASSIGN,
  &&lbl_BOOLNOT,
  &&lbl_ADDINT,
  &&lbl_SUBINT,
  &&lbl_MULINT,
  &&lbl_DIVINT,
  &&lbl_MODINT,
  &&lbl_ANDINT,
  &&lbl_ORINT,
  &&lbl_XORINT,
  &&lbl_SHIFTLEFTINT,
  &&lbl_SHIFTRIGHTINTSIGNED,
  &&lbl_SHIFTRIGHTINTUNSIGNED,
  &&lbl_EQ,
  &&lbl_NEQ,
  &&lbl_LTINT,
  &&lbl_GTINT,
  &&lbl_LEINT,
  &&lbl_GEINT,
  &&lbl_FLOATOFINT,
  &&lbl_SMLNEGFLOAT,
  &&lbl_SMLADDFLOAT,
  &&lbl_SMLSUBFLOAT,
  &&lbl_SMLMULFLOAT,
  &&lbl_SMLDIVFLOAT,
  &&lbl_INTOFFLOAT,
  &&lbl_EQFLOAT,
  &&lbl_NEQFLOAT,
  &&lbl_LTFLOAT,
  &&lbl_GTFLOAT,
  &&lbl_LEFLOAT,
  &&lbl_GEFLOAT,
  &&lbl_STRINGLENGTH,
  &&lbl_GETSTRINGCHAR,
  &&lbl_SETSTRINGCHAR,
  &&lbl_EQSTRING,
  &&lbl_NEQSTRING,
  &&lbl_LTSTRING,
  &&lbl_GTSTRING,
  &&lbl_LESTRING,
  &&lbl_GESTRING,
  &&lbl_MAKEVECTOR,
  &&lbl_VECTLENGTH,
  &&lbl_GETVECTITEM,
  &&lbl_SETVECTITEM,
  &&lbl_SMLNEGINT,
  &&lbl_SMLSUCCINT,
  &&lbl_SMLPREDINT,
  &&lbl_SMLADDINT,
  &&lbl_SMLSUBINT,
  &&lbl_SMLMULINT,
  &&lbl_SMLDIVINT,
  &&lbl_SMLMODINT,
  &&lbl_MAKEREFVECTOR,
  &&lbl_SMLQUOTINT,
  &&lbl_SMLREMINT,
  &&lbl_CHECK_SIGNALS,
  &&lbl_STOP,
  &&lbl_EQUNSIGN,
  &&lbl_NEQUNSIGN,
  &&lbl_LTUNSIGN,
  &&lbl_GTUNSIGN,
  &&lbl_LEUNSIGN,
  &&lbl_GEUNSIGN
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
, &&lbl_EVENT
