# Plan 9 mkfile for mosmldep

INCLUDES=-I ../compiler
COMPFLAGS=$INCLUDES
LINKFLAGS=-g $INCLUDES

<../mkfile.inc

# x=`{if (! test -f ../compiler/Config.ui) @{cd ../compiler; mk; cd ../toolssrc}}

OBJS = \
	Deppars.uo Deplex.uo Mosmldep.uo

LIBOBJS = \
	Obj.uo Nonstdio.uo Lexing.uo Parsing.uo

CLIBOBJS = \
	Hasht.uo Fnlib.uo Config.uo

all:V: 
	mk cutdeps mosmldep

mosmldep: $OBJS
	$MOSMLL $LINKFLAGS -noheader -o mosmldep Mosmldep.uo

cutdeps: cutdeps.uo
	$MOSMLL $LINKFLAGS -noheader -o cutdeps cutdeps.uo

Deppars.sml Deppars.sig: Deppars.grm
	$MOSMLYACC Deppars.grm

clean:
	rm -f *.ui
	rm -f *.uo
	rm -f Makefile.bak
	rm -f Deppars.sig Deppars.sml Deplex.sig Deplex.sml Mosmldep.sml
	rm -f cutdeps mosmldep

install: mosmldep cutdeps
	test -d /sys/lib/mosml/tools || mkdir /sys/lib/mosml/tools
	cp $prereq /sys/lib/mosml/tools

# depend: Deplex.sml Deppars.sml Mosmldep.sml
# 	rm -f Makefile.bak
# 	mv Makefile Makefile.bak
# 	$MOSMLCUT < Makefile.bak > Makefile
# 	$MOSMLDEP >> Makefile

### DO NOT DELETE THIS LINE
Mosmldep.uo: Deppars.ui Deplex.uo 
Deppars.uo: Deppars.ui 
Deplex.uo: Deppars.ui 
Smltope.uo: Smltope.ui Deplex.uo Deppars.ui 
Maine.uo: Maine.ui Smltope.ui 
