</$objtype/mkfile

TARG=mosmlyac
HFILES=defs.h
OFILES=\
	closure.$O\
	error.$O\
	lalr.$O\
	lr0.$O\
	main.$O\
	mkpar.$O\
	output.$O\
	reader.$O\
	skeleton.$O\
	symtab.$O\
	verbose.$O\
	warshall.$O\

BIN=/$objtype/bin/aux
</sys/src/cmd/mkone

CC=pcc
CFLAGS=-B -D_POSIX_SOURCE -D_BSD_EXTENSION -Dplan9 -Dunix -DT$objtype -c
