<../mkfile.inc
COMPFLAGS=-I ../compiler
LINKFLAGS=-I ../compiler

MOSMLC=aux/camlrunm /sys/lib/mosml/mosmlcmp -stdlib /sys/lib/mosml

LIBOBJS=\
    List.uo Vector.uo Array.uo Strbase.uo Char.uo String.uo StringCvt.uo \
    Word.uo Word8.uo Word8Vector.uo Word8Array.uo CharVector.uo CharArray.uo \
    Obj.uo BasicIO.uo Nonstdio.uo Lexing.uo Parsing.uo

EXTOBJS=\
    Miscsys.uo Printexc.uo Filename.uo Fnlib.uo Sort.uo \
    Arg.uo Hasht.uo

OBJS=\
    Syntax.uo Scan_aux.uo Gram_aux.uo Grammar.uo Scanner.uo \
    Lexgen.uo Output.uo Mainlex.uo

all:V: mosmllex

mosmllex: $OBJS
	$MOSMLL $LINKFLAGS -noheader -o mosmllex Mainlex.uo

nuke clean:V:
	rm -f *.ui *.uo mosmllex mosmllex.bin Grammar.sml Grammar.sig \
		Grammar.output Scanner.sml

install:V: mosmllex
	cp mosmllex /sys/lib/mosml

Grammar.sml Grammar.sig: Grammar.grm
	$MOSMLYACC Grammar.grm

### DO NOT DELETE THIS LINE
Grammar.ui: Syntax.uo 
Grammar.uo: Grammar.ui Syntax.uo Gram_aux.uo 
Scanner.uo: Scanner.ui Syntax.uo Scan_aux.uo Grammar.ui 
Gram_aux.uo: Syntax.uo 
Output.uo: Syntax.uo 
Mainlex.uo: Lexgen.uo Syntax.uo Scan_aux.uo Scanner.ui Grammar.ui Output.uo 
Scanner.ui: Grammar.ui 
Lexgen.uo: Syntax.uo 
